# Generated by Django 4.2.2 on 2024-10-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0004_deployed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('GeoLoc', models.CharField(max_length=10)),
            ],
        ),
    ]
