# Generated by Django 4.2.2 on 2024-10-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0005_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaintenance',
            name='CatNum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partmaintenance',
            name='EQP_ID',
            field=models.CharField(max_length=15),
        ),
    ]
