# Generated by Django 4.2.2 on 2024-10-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0006_alter_partmaintenance_catnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='GeoLoc',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
